package com.app.speak.ui.utils

import com.app.speak.models.CountryCode

object Constants {

    val codes = listOf(
        CountryCode(countryName = "Afghanistan", alphaCode = "AF"),
        CountryCode(countryName = "Albania", alphaCode = "AL"),
        CountryCode(countryName = "Algeria", alphaCode = "DZ"),
        CountryCode(countryName = "American Samoa", alphaCode = "AS"),
        CountryCode(countryName = "Andorra", alphaCode = "AD"),
        CountryCode(countryName = "Angola", alphaCode = "AO"),
        CountryCode(countryName = "Anguilla", alphaCode = "AI"),
        CountryCode(countryName = "Antarctica", alphaCode = "AQ"),
        CountryCode(countryName = "Antigua and Barbuda", alphaCode = "AG"),
        CountryCode(countryName = "Argentina", alphaCode = "AR"),
        CountryCode(countryName = "Armenia", alphaCode = "AM"),
        CountryCode(countryName = "Aruba", alphaCode = "AW"),
        CountryCode(countryName = "Australia", alphaCode = "AU"),
        CountryCode(countryName = "Austria", alphaCode = "AT"),
        CountryCode(countryName = "Azerbaijan", alphaCode = "AZ"),
        CountryCode(countryName = "Bahamas ", alphaCode = "BS"),
        CountryCode(countryName = "Bahrain", alphaCode = "BH"),
        CountryCode(countryName = "Bangladesh", alphaCode = "BD"),
        CountryCode(countryName = "Barbados", alphaCode = "BB"),
        CountryCode(countryName = "Belarus", alphaCode = "BY"),
        CountryCode(countryName = "Belgium", alphaCode = "BE"),
        CountryCode(countryName = "Belize", alphaCode = "BZ"),
        CountryCode(countryName = "Benin", alphaCode = "BJ"),
        CountryCode(countryName = "Bermuda", alphaCode = "BM"),
        CountryCode(countryName = "Bhutan", alphaCode = "BT"),
        CountryCode(countryName = "Bolivia (Plurinational State of)", alphaCode = "BO"),
        CountryCode(countryName = "Bonaire, Sint Eustatius and Saba", alphaCode = "BQ"),
        CountryCode(countryName = "Bosnia and Herzegovina", alphaCode = "BA"),
        CountryCode(countryName = "Botswana", alphaCode = "BW"),
        CountryCode(countryName = "Bouvet Island", alphaCode = "BV"),
        CountryCode(countryName = "Brazil", alphaCode = "BR"),
        CountryCode(countryName = "British Indian Ocean Territory ", alphaCode = "IO"),
        CountryCode(countryName = "Brunei Darussalam", alphaCode = "BN"),
        CountryCode(countryName = "Bulgaria", alphaCode = "BG"),
        CountryCode(countryName = "Burkina Faso", alphaCode = "BF"),
        CountryCode(countryName = "Burundi", alphaCode = "BI"),
        CountryCode(countryName = "Cabo Verde", alphaCode = "CV"),
        CountryCode(countryName = "Cambodia", alphaCode = "KH"),
        CountryCode(countryName = "Cameroon", alphaCode = "CM"),
        CountryCode(countryName = "Canada", alphaCode = "CA"),
        CountryCode(countryName = "Cayman Islands ", alphaCode = "KY"),
        CountryCode(countryName = "Central African Republic ", alphaCode = "CF"),
        CountryCode(countryName = "Chad", alphaCode = "TD"),
        CountryCode(countryName = "Chile", alphaCode = "CL"),
        CountryCode(countryName = "China", alphaCode = "CN"),
        CountryCode(countryName = "Christmas Island", alphaCode = "CX"),
        CountryCode(countryName = "Cocos (Keeling) Islands ", alphaCode = "CC"),
        CountryCode(countryName = "Colombia", alphaCode = "CO"),
        CountryCode(countryName = "Comoros ", alphaCode = "KM"),
        CountryCode(countryName = "Congo, (Kinshasa)", alphaCode = "CD"),
        CountryCode(countryName = "Congo (Brazzaville)  ", alphaCode = "CG"),
        CountryCode(countryName = "Cook Islands ", alphaCode = "CK"),
        CountryCode(countryName = "Costa Rica", alphaCode = "CR"),
        CountryCode(countryName = "Croatia", alphaCode = "HR"),
        CountryCode(countryName = "Cuba", alphaCode = "CU"),
        CountryCode(countryName = "Curaçao", alphaCode = "CW"),
        CountryCode(countryName = "Cyprus", alphaCode = "CY"),
        CountryCode(countryName = "Czechia", alphaCode = "CZ"),
        CountryCode(countryName = "Côte d'Ivoire", alphaCode = "CI"),
        CountryCode(countryName = "Denmark", alphaCode = "DK"),
        CountryCode(countryName = "Djibouti", alphaCode = "DJ"),
        CountryCode(countryName = "Dominica", alphaCode = "DM"),
        CountryCode(countryName = "Dominican Republic ", alphaCode = "DO"),
        CountryCode(countryName = "Ecuador", alphaCode = "EC"),
        CountryCode(countryName = "Egypt", alphaCode = "EG"),
        CountryCode(countryName = "El Salvador", alphaCode = "SV"),
        CountryCode(countryName = "Equatorial Guinea", alphaCode = "GQ"),
        CountryCode(countryName = "Eritrea", alphaCode = "ER"),
        CountryCode(countryName = "Estonia", alphaCode = "EE"),
        CountryCode(countryName = "Eswatini", alphaCode = "SZ"),
        CountryCode(countryName = "Ethiopia", alphaCode = "ET"),
        CountryCode(countryName = "Falkland Islands  [Malvinas]", alphaCode = "FK"),
        CountryCode(countryName = "Faroe Islands ", alphaCode = "FO"),
        CountryCode(countryName = "Fiji", alphaCode = "FJ"),
        CountryCode(countryName = "Finland", alphaCode = "FI"),
        CountryCode(countryName = "France", alphaCode = "FR"),
        CountryCode(countryName = "French Guiana", alphaCode = "GF"),
        CountryCode(countryName = "French Polynesia", alphaCode = "PF"),
        CountryCode(countryName = "French Southern Territories ", alphaCode = "TF"),
        CountryCode(countryName = "Gabon", alphaCode = "GA"),
        CountryCode(countryName = "Gambia ", alphaCode = "GM"),
        CountryCode(countryName = "Georgia", alphaCode = "GE"),
        CountryCode(countryName = "Germany", alphaCode = "DE"),
        CountryCode(countryName = "Ghana", alphaCode = "GH"),
        CountryCode(countryName = "Gibraltar", alphaCode = "GI"),
        CountryCode(countryName = "Greece", alphaCode = "GR"),
        CountryCode(countryName = "Greenland", alphaCode = "GL"),
        CountryCode(countryName = "Grenada", alphaCode = "GD"),
        CountryCode(countryName = "Guadeloupe", alphaCode = "GP"),
        CountryCode(countryName = "Guam", alphaCode = "GU"),
        CountryCode(countryName = "Guatemala", alphaCode = "GT"),
        CountryCode(countryName = "Guernsey", alphaCode = "GG"),
        CountryCode(countryName = "Guinea", alphaCode = "GN"),
        CountryCode(countryName = "Guinea-Bissau", alphaCode = "GW"),
        CountryCode(countryName = "Guyana", alphaCode = "GY"),
        CountryCode(countryName = "Haiti", alphaCode = "HT"),
        CountryCode(countryName = "Heard Island and McDonald Islands", alphaCode = "HM"),
        CountryCode(countryName = "Holy See ", alphaCode = "VA"),
        CountryCode(countryName = "Honduras", alphaCode = "HN"),
        CountryCode(countryName = "Hong Kong", alphaCode = "HK"),
        CountryCode(countryName = "Hungary", alphaCode = "HU"),
        CountryCode(countryName = "Iceland", alphaCode = "IS"),
        CountryCode(countryName = "India", alphaCode = "IN"),
        CountryCode(countryName = "Indonesia", alphaCode = "ID"),
        CountryCode(countryName = "Iran (Islamic Republic of)", alphaCode = "IR"),
        CountryCode(countryName = "Iraq", alphaCode = "IQ"),
        CountryCode(countryName = "Ireland", alphaCode = "IE"),
        CountryCode(countryName = "Isle of Man", alphaCode = "IM"),
        CountryCode(countryName = "Israel", alphaCode = "IL"),
        CountryCode(countryName = "Italy", alphaCode = "IT"),
        CountryCode(countryName = "Jamaica", alphaCode = "JM"),
        CountryCode(countryName = "Japan", alphaCode = "JP"),
        CountryCode(countryName = "Jersey", alphaCode = "JE"),
        CountryCode(countryName = "Jordan", alphaCode = "JO"),
        CountryCode(countryName = "Kazakhstan", alphaCode = "KZ"),
        CountryCode(countryName = "Kenya", alphaCode = "KE"),
        CountryCode(countryName = "Kiribati", alphaCode = "KI"),
        CountryCode(countryName = "Korea (the Democratic People's Republic of)", alphaCode = "KP"),
        CountryCode(countryName = "Korea (the Republic of)", alphaCode = "KR"),
        CountryCode(countryName = "Kuwait", alphaCode = "KW"),
        CountryCode(countryName = "Kyrgyzstan", alphaCode = "KG"),
        CountryCode(countryName = "Lao People's Democratic Republic ", alphaCode = "LA"),
        CountryCode(countryName = "Latvia", alphaCode = "LV"),
        CountryCode(countryName = "Lebanon", alphaCode = "LB"),
        CountryCode(countryName = "Lesotho", alphaCode = "LS"),
        CountryCode(countryName = "Liberia", alphaCode = "LR"),
        CountryCode(countryName = "Libya", alphaCode = "LY"),
        CountryCode(countryName = "Liechtenstein", alphaCode = "LI"),
        CountryCode(countryName = "Lithuania", alphaCode = "LT"),
        CountryCode(countryName = "Luxembourg", alphaCode = "LU"),
        CountryCode(countryName = "Macao", alphaCode = "MO"),
        CountryCode(countryName = "Madagascar", alphaCode = "MG"),
        CountryCode(countryName = "Malawi", alphaCode = "MW"),
        CountryCode(countryName = "Malaysia", alphaCode = "MY"),
        CountryCode(countryName = "Maldives", alphaCode = "MV"),
        CountryCode(countryName = "Mali", alphaCode = "ML"),
        CountryCode(countryName = "Malta", alphaCode = "MT"),
        CountryCode(countryName = "Marshall Islands ", alphaCode = "MH"),
        CountryCode(countryName = "Martinique", alphaCode = "MQ"),
        CountryCode(countryName = "Mauritania", alphaCode = "MR"),
        CountryCode(countryName = "Mauritius", alphaCode = "MU"),
        CountryCode(countryName = "Mayotte", alphaCode = "YT"),
        CountryCode(countryName = "Mexico", alphaCode = "MX"),
        CountryCode(countryName = "Micronesia (Federated States of)", alphaCode = "FM"),
        CountryCode(countryName = "Moldova (the Republic of)", alphaCode = "MD"),
        CountryCode(countryName = "Monaco", alphaCode = "MC"),
        CountryCode(countryName = "Mongolia", alphaCode = "MN"),
        CountryCode(countryName = "Montenegro", alphaCode = "ME"),
        CountryCode(countryName = "Montserrat", alphaCode = "MS"),
        CountryCode(countryName = "Morocco", alphaCode = "MA"),
        CountryCode(countryName = "Mozambique", alphaCode = "MZ"),
        CountryCode(countryName = "Myanmar", alphaCode = "MM"),
        CountryCode(countryName = "Namibia", alphaCode = "NA"),
        CountryCode(countryName = "Nauru", alphaCode = "NR"),
        CountryCode(countryName = "Nepal", alphaCode = "NP"),
        CountryCode(countryName = "Netherlands ", alphaCode = "NL"),
        CountryCode(countryName = "New Caledonia", alphaCode = "NC"),
        CountryCode(countryName = "New Zealand", alphaCode = "NZ"),
        CountryCode(countryName = "Nicaragua", alphaCode = "NI"),
        CountryCode(countryName = "Niger ", alphaCode = "NE"),
        CountryCode(countryName = "Nigeria", alphaCode = "NG"),
        CountryCode(countryName = "Niue", alphaCode = "NU"),
        CountryCode(countryName = "Norfolk Island", alphaCode = "NF"),
        CountryCode(countryName = "Northern Mariana Islands ", alphaCode = "MP"),
        CountryCode(countryName = "Norway", alphaCode = "NO"),
        CountryCode(countryName = "Oman", alphaCode = "OM"),
        CountryCode(countryName = "Pakistan", alphaCode = "PK"),
        CountryCode(countryName = "Palau", alphaCode = "PW"),
        CountryCode(countryName = "Palestine, State of", alphaCode = "PS"),
        CountryCode(countryName = "Panama", alphaCode = "PA"),
        CountryCode(countryName = "Papua New Guinea", alphaCode = "PG"),
        CountryCode(countryName = "Paraguay", alphaCode = "PY"),
        CountryCode(countryName = "Peru", alphaCode = "PE"),
        CountryCode(countryName = "Philippines ", alphaCode = "PH"),
        CountryCode(countryName = "Pitcairn", alphaCode = "PN"),
        CountryCode(countryName = "Poland", alphaCode = "PL"),
        CountryCode(countryName = "Portugal", alphaCode = "PT"),
        CountryCode(countryName = "Puerto Rico", alphaCode = "PR"),
        CountryCode(countryName = "Qatar", alphaCode = "QA"),
        CountryCode(countryName = "Republic of North Macedonia", alphaCode = "MK"),
        CountryCode(countryName = "Romania", alphaCode = "RO"),
        CountryCode(countryName = "Russian Federation ", alphaCode = "RU"),
        CountryCode(countryName = "Rwanda", alphaCode = "RW"),
        CountryCode(countryName = "Réunion", alphaCode = "RE"),
        CountryCode(countryName = "Saint Barthélemy", alphaCode = "BL"),
        CountryCode(countryName = "Saint Helena, Ascension and Tristan da Cunha", alphaCode = "SH"),
        CountryCode(countryName = "Saint Kitts and Nevis", alphaCode = "KN"),
        CountryCode(countryName = "Saint Lucia", alphaCode = "LC"),
        CountryCode(countryName = "Saint Martin (French part)", alphaCode = "MF"),
        CountryCode(countryName = "Saint Pierre and Miquelon", alphaCode = "PM"),
        CountryCode(countryName = "Saint Vincent and the Grenadines", alphaCode = "VC"),
        CountryCode(countryName = "Samoa", alphaCode = "WS"),
        CountryCode(countryName = "San Marino", alphaCode = "SM"),
        CountryCode(countryName = "Sao Tome and Principe", alphaCode = "ST"),
        CountryCode(countryName = "Saudi Arabia", alphaCode = "SA"),
        CountryCode(countryName = "Senegal", alphaCode = "SN"),
        CountryCode(countryName = "Serbia", alphaCode = "RS"),
        CountryCode(countryName = "Seychelles", alphaCode = "SC"),
        CountryCode(countryName = "Sierra Leone", alphaCode = "SL"),
        CountryCode(countryName = "Singapore", alphaCode = "SG"),
        CountryCode(countryName = "Sint Maarten (Dutch part)", alphaCode = "SX"),
        CountryCode(countryName = "Slovakia", alphaCode = "SK"),
        CountryCode(countryName = "Slovenia", alphaCode = "SI"),
        CountryCode(countryName = "Solomon Islands", alphaCode = "SB"),
        CountryCode(countryName = "Somalia", alphaCode = "SO"),
        CountryCode(countryName = "South Africa", alphaCode = "ZA"),
        CountryCode(countryName = "South Georgia and the South Sandwich Islands", alphaCode = "GS"),
        CountryCode(countryName = "South Sudan", alphaCode = "SS"),
        CountryCode(countryName = "Spain", alphaCode = "ES"),
        CountryCode(countryName = "Sri Lanka", alphaCode = "LK"),
        CountryCode(countryName = "Sudan ", alphaCode = "SD"),
        CountryCode(countryName = "Suriname", alphaCode = "SR"),
        CountryCode(countryName = "Svalbard and Jan Mayen", alphaCode = "SJ"),
        CountryCode(countryName = "Sweden", alphaCode = "SE"),
        CountryCode(countryName = "Switzerland", alphaCode = "CH"),
        CountryCode(countryName = "Syrian Arab Republic", alphaCode = "SY"),
        CountryCode(countryName = "Taiwan (Province of China)", alphaCode = "TW"),
        CountryCode(countryName = "Tajikistan", alphaCode = "TJ"),
        CountryCode(countryName = "Tanzania, United Republic of", alphaCode = "TZ"),
        CountryCode(countryName = "Thailand", alphaCode = "TH"),
        CountryCode(countryName = "Timor-Leste", alphaCode = "TL"),
        CountryCode(countryName = "Togo", alphaCode = "TG"),
        CountryCode(countryName = "Tokelau", alphaCode = "TK"),
        CountryCode(countryName = "Tonga", alphaCode = "TO"),
        CountryCode(countryName = "Trinidad and Tobago", alphaCode = "TT"),
        CountryCode(countryName = "Tunisia", alphaCode = "TN"),
        CountryCode(countryName = "Turkey", alphaCode = "TR"),
        CountryCode(countryName = "Turkmenistan", alphaCode = "TM"),
        CountryCode(countryName = "Turks and Caicos Islands ", alphaCode = "TC"),
        CountryCode(countryName = "Tuvalu", alphaCode = "TV"),
        CountryCode(countryName = "Uganda", alphaCode = "UG"),
        CountryCode(countryName = "Ukraine", alphaCode = "UA"),
        CountryCode(countryName = "United Arab Emirates ", alphaCode = "AE"),
        CountryCode(
            countryName = "United Kingdom of Great Britain and Northern Ireland ",
            alphaCode = "GB"
        ),
        CountryCode(countryName = "United States Minor Outlying Islands ", alphaCode = "UM"),
        CountryCode(countryName = "United States of America ", alphaCode = "US"),
        CountryCode(countryName = "Uruguay", alphaCode = "UY"),
        CountryCode(countryName = "Uzbekistan", alphaCode = "UZ"),
        CountryCode(countryName = "Vanuatu", alphaCode = "VU"),
        CountryCode(countryName = "Venezuela (Bolivarian Republic)", alphaCode = "VE"),
        CountryCode(countryName = "Viet Nam", alphaCode = "VN"),
        CountryCode(countryName = "Virgin Islands (British)", alphaCode = "VG"),
        CountryCode(countryName = "Virgin Islands (U.S.)", alphaCode = "VI"),
        CountryCode(countryName = "Wallis and Futuna", alphaCode = "WF"),
        CountryCode(countryName = "Western Sahara", alphaCode = "EH"),
        CountryCode(countryName = "Yemen", alphaCode = "YE"),
        CountryCode(countryName = "Zambia", alphaCode = "ZM"),
        CountryCode(countryName = "Zimbabwe", alphaCode = "ZW")
    )
}